change overflow hidden to auto
VikeLabs/courseup pull request #211
Opened 2021-06-11 16:16 UTC by chsunwoo1002

## Overview

Closes #209 

website cut off the text because overflow is set to hidden.
Change the setting to auto

<img width="1280" alt="Screen Shot 2021-06-11 at 9 13 04 AM" src="https://user-images.githubusercontent.com/24921825/121716917-795ce100-ca95-11eb-9c03-09876745694c.png">

2021-06-12 01:04 UTC, keithradford approved these changes
LGTM. 

The original reason we added `hidden` was to fix 2 scroll-bars showing up on the right-side (on the main content and for the whole page) so this fixed it. Verified and your changes seem to still work for that 👍 

Thanks! :)

2021-06-12 02:47 UTC, aomi requested changes
This doesn't fix it. You get scrolling as a result. If you take out the `height` property somewhere near this stuff (I forgot where I'm on mobile right now)

2021-06-12 16:15 UTC, keithradford commented
> This doesn't fix it. You get scrolling as a result. If you take out the `height: 100%` property somewhere near this stuff (I forgot where I'm on mobile right now) it will fix this problem.

You get scrolling, but I didn't think that was that big of a deal. I guess we can aim to make it more responsive instead?

2021-08-05 04:11 UTC, aomi commented
Going to close due to inactivity.

2021-08-05 04:11 UTC, closed without merging