Adds info for kick off to top banner
VikeLabs/courseup pull request #501
Opened 2023-09-09 21:46 UTC by liamshatzel

# Description

Added info for kick-off to top banner with link to vikelabs.ca. Would it be good to also change banner color on kick off info to something like red??

## Screenshots

### Before

### After

## Checklist

- [ x] The code follows all style guidelines.
- [ x] The code passes all required tests.
- [ ] The code is documented.
- [ ] The code includes tests.
- [ x] I have self-reviewed my changes and have done QA.

## General Comments

2023-09-10 05:43 UTC, JoshoTheMosho approved these changes
LGTM!

2023-09-10 06:40 UTC, JoshoTheMosho requested changes
Just noticed failing tests for security issue

2023-09-10 06:40 UTC, JoshoTheMosho commented on src/common/header/containers/HeaderContainer.tsx
> +          <a href="https://vikelabs.ca/kickoff" style={{ textDecoration: 'underline' }} target="_blank">
```suggestion
          <a href="https://vikelabs.ca/kickoff" style={{ textDecoration: 'underline' }} target="_blank" rel="noreferrer">
```

2023-09-10 06:40 UTC, JoshoTheMosho commented on src/common/header/containers/HeaderContainer.tsx
> +          <a href="https://vikelabs.ca/kickoff" style={{ textDecoration: 'underline' }} target="_blank">
```suggestion
          <a href="https://vikelabs.ca/kickoff" style={{ textDecoration: 'underline' }} target="_blank" rel="noreferrer">
```

2023-09-11 17:15 UTC, szeckirjr approved these changes
besides what Josh said, LGTM too

2023-09-11 17:17 UTC, liamshatzel commented on src/common/header/containers/HeaderContainer.tsx
> +          <a href="https://vikelabs.ca/kickoff" style={{ textDecoration: 'underline' }} target="_blank">
71d7f603d25c7778a7bf9e0256b020222886f9b7

2023-09-11 17:18 UTC, liamshatzel commented on src/common/header/containers/HeaderContainer.tsx
> +          <a href="https://vikelabs.ca/kickoff" style={{ textDecoration: 'underline' }} target="_blank">
c772b0df2ea057a31a4202eb1fa217a40c43f6a7

2023-09-11 17:28 UTC, szeckirjr commented
run `npm run lint:fix` to fix CI linting errors btw 👀

2023-09-12 04:15 UTC, szeckirjr approved these changes
kick off on sep 18th 🚀

2023-09-13 23:52 UTC, JoshoTheMosho approved these changes
LGTM

2023-09-14 00:01 UTC, merged